image: ubuntu

build_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:/usr/local/sbin:/usr/local/bin:$PATH"
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable.tar.gz
  - tar xf libsodium-1.0.18-stable.tar.gz
  - cd libsodium-stable && ./configure && make check && sudo make install

test_script:
  - cargo test --verbose
  - cargo test --verbose --release
  - cargo test --verbose --features="use-maproper-volatile"
  - cargo test --verbose --release --features="use-maproper-volatile"
